### ISSUE TITLE
Sankey not working on server location... 

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1261]
Sankey not working on Gryd.  I can't reproduce the error on my local machine... 

```python 
ImportErrorTraceback (most recent call last)
<ipython-input-18-dbeed4035d92> in <module>()
----> 1 from gpkit.interactive import sankey

/home/gryduser/work/gpkit/gpkit/interactive/sankey.py in <module>()
      1 "implements Sankey"
      2 from collections import defaultdict
----> 3 from ipysankeywidget import SankeyWidget  # pylint: disable=import-error
      4 from gpkit import ConstraintSet, Model
      5 from gpkit import GeometricProgram, SequentialGeometricProgram

ImportError: No module named ipysankeywidget
```

**Comment by mjburton11** [comment]
I didn't install ipysankeywidget so I'm an idiot

**Comment by mjburton11** [comment]
Ok installed ipysankeywidget and it is working, however I can't see the diagram.

**Comment by bqpd** [comment]
How can I get a gryd account to test this myself?

**Comment by bqpd** [comment]
The problem is that you can't enable this extension as a widget: the
command `jupyter nbextension enable ipysankeywidget` returns `Permission
denied` because gryd users are not permitted to modify their notebook.json
...

Many other extensions are loaded through the nbextensions plugin, but
sankey does not appear to be available. Can we ask the gryd developers to
either add it to that list or suggest a way for us to add new widgets
ourselves?
