### ISSUE TITLE
Error with exec parse_variables()

### ISSUE THREAD

**Issue by courtin** [convexengineering/gpkit#1298]
@bqpd I'm seeing an unexpected error with the parse_variables functionality in this here - https://github.com/convexengineering/gplibrary/blob/b49b7b16dedddd5aea369e3d7c8faacd04f76668/gpkitmodels/GP/aircraft/prop/propeller.py#L144-L158

This seems to be caused by the code in L176 - https://github.com/convexengineering/gplibrary/blob/b49b7b16dedddd5aea369e3d7c8faacd04f76668/gpkitmodels/GP/aircraft/prop/propeller.py#L175-L176.  This is a cumbersome way of doing the summation but shouldn't be illegal.  The syntax used in L175 doesn't cause the error.

**Comment by courtin** [comment]
Commit hash: b49b7b16dedddd5aea369e3d7c8faacd04f76668

run prop_test.py to reproduce

**Comment by bqpd** [comment]
can reproduce, debugging...

**Comment by bqpd** [comment]
Okay, so it's complaining about the list comprehension (which is a bit odd, since we have those elsewhere, but...)

There's two fixes, the better specific one and the general one:

*specific*
replace 
```python
TCS([Q >= sum(blade["dQ"][n] for n in range(N))]),
```
with 
```python
TCS([Q >= blade.dQ[:N].cumsum()]),
```
, which is faster (no string access, uses numpy built-in) and a bit cleaner...

*general*
replace
```python
exec parse_variables(MultiElementProp.__doc__)
```
with 
```python
exec parse_variables(MultiElementProp.__doc__) in locals()
```
which explicitly specifies the context to do the exec in.
