### ISSUE TITLE
non-improving objective cost could still be under reltol? 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1348]
has to do with the error:
```python
SP is not converging! Last GP iteration had a higher cost (2.4e+03) than the previous one (2.3e+03). Results for each iteration are in (Model).program.results. If your model contains SignomialEqualities, note that convergence is not guaranteed: try replacing any SigEqs you can and solving again.
```
Since we calculate the objective improvement against reltol as follows:
```python
            if abs(reldiff(self(key), sol(key))) >= reltol:
                return False
``` 
you could theoretically have a worsening objective and still terminate the solve.

**Comment by 1ozturkbe** [comment]
@bqpd this makes sense right? Definitely we should fix.

**Comment by bqpd** [comment]
are you looking at the [current version](https://github.com/convexengineering/gpkit/blob/master/gpkit/constraints/sgp.py#L138) of this file?

currently the logic is as follows:
- if it's the first or second solution, don't check relative improvement
- if the solution has worsened by more than reltol, raise the error
- if the solution has improved by less than reltol, loop again

thus, a pass-band with a radius of reltol is made around the solution; anything in this band is seen as convergence, while anything outside of it is either an error or a continuation.

this does allow "worse" solutions to be returned, but only if they are within user-specified reltol; the assumption here is that there may be some numerical noise around the solution.

I'm open to making the pass-band not symmetric, but that's why it is right now.

**Comment by bqpd** [comment]
(closing pending Berk's response)

**Comment by 1ozturkbe** [comment]
@bqpd I see what you are saying. My intuition was that it is possible that, during a single GP step, the solution could worsen an amount less than reltol, causing a premature termination of the SP solve. This may turn out not to be an issue, but it is technically possible.

**Comment by bqpd** [comment]
yup that's possible...currently we just call that convergence :p
