### ISSUE TITLE
preparing to only support python3

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#1450]
- [ ] add to python3 pypi
  - [x] change assumed string formatting to python3 only (and remove python2-specific code)

**Comment by 1ozturkbe** [comment]
@bqpd it's my opinion that we should make this change as soon as possible, since it would be nice to finally have some uniformity in both the solver and the language versions. To get this ball rolling, I created a py3only branch where I went through the conversion. I also commented with ```#TODO: PY3``` at places where I was unsure what to do.

**Comment by 1ozturkbe** [comment]
The py2/py3 discrepancy is already creating issues [in robust](https://github.com/convexengineering/robust/pull/52) so I'd like to have this resolved soon.

**Comment by bqpd** [comment]
This should only require changing a few things in repr_conventions.py!

**Comment by 1ozturkbe** [comment]
But also all of the imports of ```future``` in python, as well as lots of ```list()``` additions. Just check out the branch.

**Comment by 1ozturkbe** [comment]
(I had to purge all of the things that allowed for compatibility of both versions.)

**Comment by bqpd** [comment]
see https://github.com/convexengineering/gpkit/pull/1463 !
