### ISSUE TITLE
Not free

### ISSUE THREAD

**Issue by pjuangph** [convexengineering/gpkit#1574]
Why are you guys using Mosek? This is not free or open source.

**Comment by bqpd** [comment]
We do support CVXOPT, which is free and open source, but is not as capable with MOSEK. This might be because of MOSEK's presolver (CVXOPT does not have one) or because of its solver. Unfortunately efforts to see if other open source solvers such as SCS or ECOS could be a sufficient alternative to replace MOSEK have stalled -- would love a PR on that if you want to look into it!
