### ISSUE TITLE
add legend/colorbar to SensitivityMap

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#451]
and/or quantize the colors, providing a map/like reference to the range of sensitivities associated with each shade.

**Comment by aechevarria1** [comment]
Gonna take a jab at this

**Comment by bqpd** [comment]
Great! I was looking into using `\rule`: http://tex.stackexchange.com/questions/106984/how-to-draw-a-square-of-1cm-in-latex-filled-with-color

**Comment by aechevarria1** [comment]
I have a question. When I run display(SensitivityMap(m,paintkey=key)), I get <gpkit.interactive.sensitivity_map.SensitivityMap at 0x7f9dcb460190> as a return but nothing displayed, do I need a Latex editor to view this? Additionally, the comments in the SensitivityMap class code state to do a for loop through model.solution["sensitivities"] and run display multiple times. However the code also states that the paintkey input must be "constants", "monomials", or "posynomials" I'm using the Simple Wing example from the documentation, and the keys that print out are "la", "nu", "constants", and "constraint", so I get multiple unhashable type errors until I hit the "constants" key. I was thinking it could be good to add an if statement to that for loop so that it doesn't run display on keys that aren't "constants", "monomials", or "posynomials"

**Comment by whoburg** [comment]
I'm sure @bqpd will add more, but a couple quick comments to get started:

1. That sounds like a badly out of date sensitivity map docstring (and possibly implementation) that should be updated for the latest GPkit.
2. A unit test should also be added to prevent sensitivity map from getting out of date again.
3. For displaying, have you tried an ipython notebook?

**Comment by aechevarria1** [comment]
I get `gpkit.interactive.sensitivity_map.SensitivityMap at 0x7f9dcb460190>` as a return

**Comment by aechevarria1** [comment]
I haven't, but I was wondering if there was a way to display it only using the command line. I found pylab.show() works for displaying matplotlib figures from the command line, wasn't sure if there was one for latex as well.

**Comment by whoburg** [comment]
good question! I'm not aware of that for latex but it would sure be great if that existed (we shouldn't write it ourselves though)

The ipython notebook is a pretty good way to display though.

**Comment by aechevarria1** [comment]
Okay, I'll get ipython

**Comment by aechevarria1** [comment]
Okay, so I've managed to print rectangles colored according to the sensitivity values of each non-grey variable in latex. 
![latex printout](https://cloud.githubusercontent.com/assets/10841125/16365071/793a7e82-3bc3-11e6-813d-979f1572e262.png)
Is this what you had in mind in terms of a reference? Did you want the colors to be sorted? If so how do you want them sorted. Also, did you want to add any other information to the bar?

**Comment by aechevarria1** [comment]
![organized latex bar](https://cloud.githubusercontent.com/assets/10841125/16389506/3d67e576-3c6c-11e6-875d-870bc919e3ea.png)
Got it organized from blue to red

**Comment by bqpd** [comment]
Hmm, I wonder if you might be better off making an evenly-spaced color bar (with labels before and after) instead? @whoburg what do you think

**Comment by bqpd** [comment]
Oh whoops had an old page and didn't see the new picture. Looks good! I wonder if it should go above the minimize declaration instead? And labels at the extremes seems sufficient, the center is fairly clear...

**Comment by bqpd** [comment]
Are the boxes italicized because they're in math mode?

**Comment by aechevarria1** [comment]
I'm not sure, this is the string I use to display them `\\textcolor[rgb]{%s,%s,%s}\\blacksquare`

**Comment by aechevarria1** [comment]
So I moved the color bar and added labels on the end
![color bar](https://cloud.githubusercontent.com/assets/10841125/16537093/3202de92-3fc9-11e6-9f5e-5a4eddc16345.png)
Now I've hit an issue, this is what is displayed when I add the color list to the end of the return in this function
```python
def _repr_latex_(self):
        "iPython LaTeX representation"
        return "$$\\require{color}\n" +self.latex+"\n$$" + self.color_list
```
However, I get an error when I try to switch it to the front so that it is on top of the equations displayed
```python
def _repr_latex_(self):
        "iPython LaTeX representation"
        return self.color_list+ "$$\\require{color}\n" +self.latex+"\n$$" 
```
`TypeError: can only concatenate list (not "str") to list`

Any reason why this is?

**Comment by whoburg** [comment]
You're trying to concatenate a string to a list -- like this:

```python
In [1]: ["foo"] + "bar"
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-ec4ec586c53c> in <module>()
----> 1 ["foo"] + "bar"

TypeError: can only concatenate list (not "str") to list
```

What's in `color_list`? Try replacing `self.color_list` with `"".join(self.color_list)`.

**Comment by aechevarria1** [comment]
`self.color_list` is a list of latex colored boxes, with numbers on the end, like this, `'\\textcolor[rgb]{0.31,0.59,0.86}\\blacksquare'`. I do use join, so it turns into a single string like this `$$\textcolor{black}{-0.48}\textcolor[rgb]{0.31,0.59,0.86}\blacksquare` When I put self.color_list after joining it at the end of the return statement, it displays as expected. But if I put it before the other strings, it doesn't display. This is what is confusing me, as it seems that the order of string concatenation matters. Another thing I've noticed, is that if I try printing `self.color_list` like this
```python
def _repr_latex_(self):
        "iPython LaTeX representation"
        print self.color_list
        return "$$\\require{color}\n" +self.latex+"\n$$" + self.color_list
```
It prints out an empty list,  although the latex display prints out correctly. If I print `self.color_list` in the `def constraint_latex_list(self, paintby)` method however, it does print out the list as expected.

**Comment by aechevarria1** [comment]
I'm not sure how to make a model that will have `paintby` equal to monomial or posynomial. Could I get help with that?

**Comment by bqpd** [comment]
superseded by #1244
