### ISSUE TITLE
anonymyzing gps for debugging

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#834]
I have recently found three different cases where I think cvxopt is returning unknown when the problem is in fact posed just fine. All three cases seem to be loosely described by "not enough pressure on a certain variable".  I think this could be a genuine solver bug, but I want to post here just in case.

The previous cases were annoying, but this one seems particularly egregious. I'm afraid I can't seem to recreate a MWE, and I can't post the full model here so the description will be a bit hand wavy.

Consider a cost breakdown something like this:

```
totalcostperpass >= cost1perpass + cost2perpass + cost3perpass + cost4perpass + cost5perpass
```

where each cost has its own constraint(s)

```
cost1perpass >= cost1/numpass
cost2perpass >= cost2/numpass
etc..
```

In the interest of cleaning things up, I try the following minor change:

```
totalcostperpass >= (cost1 + cost2 + cost3 + cost4 + cost5)/numpass
```

and get rid of the `costxperpass >= costx/numpass` constraints.

Whereas the original formulation solves fine, the second one returns unknown.

Looking at the original solution, I notice cost5 is smaller than the other costs (2x smaller than the next biggest one and about 5x smaller than the biggest). I try the following and it works:

```
totalcostperpass >= (cost1 + cost2 + cost3 + cost4 )/numpass + cost5perpass,
cost5perpass >= cost5/numpass
```

Another thing works, which makes even less sense:

```
totalcostperpass >= (cost1 + cost2 + cost3 + cost4 + cost5)/numpass,
cost5perpass >= cost5/numpass
```

(removing that `cost5perpass` constraint breaks it).

Any ideas why this isn't working?

EDIT: in fact it isn't unique to `cost5`, having the following also works:

```
totalcostperpass >= (cost1 + cost2 + cost3 + cost4 + cost5)/numpass,
cost4perpass >= cost4/numpass
```

**Comment by bqpd** [comment]
That last one's a real head scratcher. Is this an SP?

**Comment by pgkirsch** [comment]
GP

**Comment by bqpd** [comment]
Dumb question, but costNperpass isn't used in any other constraints, right?

**Comment by whoburg** [comment]
This issue would really benefit from a MWE.

@pgkirsch, are you on a pip installed version of gpkit, or the latest version off master? If the former, try `m.solve(solver="cvxopt", kktsolver="ldl")`.

**Comment by pgkirsch** [comment]
Sorry forgot to reply to these. The costNperpass didn't appear anywhere else, but the numpass appeared in a couple of other "innocuous" (for want of a better word) constraints. Replacing numpass with an equivalent monomial ended up being a somewhat satisfactory solution.

RE: MWE, I know, I'm sorry I didn't provide one. If I get a chance, I can go back and try to recreate it. Something that might help this, and I'm not at all sure about how the mechanics of this would work or if it's even remotely reasonable is something that automatically "anonymizes" a GP so people working in IP-sensitive environments don't have to spend time manually converting a very descriptive GP to something more harmless so they can publish actual code on Github *cough*.

And finally, I just ran into a similar issue, that I was sure should not cause an unbounded issue so I tried your kktsolver suggestion and it totally worked! Thanks! I'm happy to close this for the time being, if that's ok with you guys.

**Comment by bqpd** [comment]
Okay, this sounds like a cvxopt bug. I'm happy to close...

**Comment by whoburg** [comment]
I've seen behavior similar to the original report, with cvxopt only (e.g. increasing the number of constraints in a well-formulated model causes it to suddenly solve as unknown). This appears to be due to the default Cholesky-based kkt solver in cvx; glad to hear the ldl fix worked. Note this has become the default on master (but hasn't been pushed to pip yet).

I like @pgkirsch's idea of an `anonymize()` method for `GeometricProgram`, which would essentially rename all the varkeys with names like `var1, var2, ...`, would drop variable descriptions, and for debugging would retain the vector status of VectorVariables (with anonymized names).

TBD whether this should be at the GP level or the Model level (if at the model level, models would be renamed to Model1, Model2, etc)

Another option is just to print out the cs, A, and p_idxs, but I think this loses some important structure that might help to debug GPkit errors vs solver errors.

I'm reopening this to at least discuss this.

I think this could be fairly straightforward to implement especially with some high-level guidance from @bqpd .
