### ISSUE TITLE
Sweep-and-plot using check boxes and text boxes in ipython notebooks 

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#852]
A request from the HLO President.

An integrated, user-friendly sweep-and-plot tool where choosing the fixed variables to sweep and the range over which to sweep them should look something like the slider settings part of `controlpanel` (i.e. check boxes and text boxes). Choosing which variable to plot should also be a check box type of thing. I'm happy to take a lead on this ticket seeing as it was requested of me for work, but would love to hear any thoughts about best approaches from @bqpd and @whoburg.

**Comment by whoburg** [comment]
This is a great ticket. Thoughts off the top of my head:

getting a prototype version where univariate sweeps are done for each plotting variable about the point set on the sliders seems totally doable.

If speed becomes an issue @bqpd and I have some ideas about faster ways to sweep (think: less points needed due to smart use of sensitivities).

To avoid dealing with 100 sliders on large models, it may make sense for controlpanel to only draw sliders for the fixed variables with the top N sensitivity magnitudes.

**Comment by bqpd** [comment]
(tbh the biggest sweep speed issue is actually gpkit inefficiencies rn, but autosweeps are going to be awesome for interactive explorations...)
